### ISSUE TITLE
Basic auth prevents health check

### ISSUE THREAD

**Issue by petschni** [18F/cf-blue-green#29]
We have a basic auth protection for our app. Unfortunately that leads to a 401 http code which is treated as an error. Could you change the check so that it does not fail the code?

```
 state     since                    cpu    memory          disk           details   
#0   running   2016-07-26 07:09:10 PM   0.0%   79.5M of 256M   110.7M of 1G      
+ curl --fail -I https://xyz-B.eu-gb.mybluemix.net
curl: (22) The requested URL returned error: 401 Unauthorised
++ on_fail
++ finally
++ rm /var/folders/gb/xyz_manifest.XXXXXXXXXX.eZF3dqmA
++ echo 'DEPLOY FAILED - you may need to check '\''cf apps'\'' and '\''cf routes'\'' and do manual cleanup'
DEPLOY FAILED - you may need to check 'cf apps' and 'cf routes' and do manual cleanup
```

**Comment by afeld** [comment]
To be honest, I recommend that folks use Autopilot instead of this project, so I don't really want to put too much more into it. I'd consider a pull request to make that configurable, though!

**Comment by petschni** [comment]
I would love to use Autopilot - but do they provide a travis integration?

**Comment by afeld** [comment]
No, but I would like them to: https://github.com/travis-ci/dpl/issues/328. The workaround is to set up custom deployment: https://docs.travis-ci.com/user/deployment/custom/. Closing since this probably isn't something we want to support in this plugin.

**Comment by rafael-nogueras** [comment]
@afeld To your knowledge, has there been any progress in integrating Autopilot with Travis? Looking through the issues boards I see you've been championing for that for a while. :-) Do you know of any project that has attempted that, so that we could see how they're doing it?

**Comment by jmcarp** [comment]
@rafael-nogueras: here's a simple example of using autopilot on travis: https://github.com/18F/epa-notice/blob/master/.travis.yml#L19-L27. It uses the `script` deploy provider, which IMO is a better idea than using the brittle provider-specific options.

**Comment by rafael-nogueras** [comment]
@jmcarp Oh, that's probably pretty much what I need: thanks! :-)

I am curious about something --and since the cf-blue-green plugin does it, too, you might know why this is the case: I would have expected to be able to configure environment variables like "CF_USERNAME" and "CF_PASSWORD" in the Travis environment variables section, instead of in the `.travis.yml` file itself, yet I see that these variables need to be embedded in `.travis.yml` so that they are available to the deploy script. Is there really no way to get around that, and be able to keep those variables within the Travis configuration?
